# Generated by Django 3.0.7 on 2020-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('laguage', models.CharField(max_length=256)),
                ('actor', models.CharField(max_length=256)),
            ],
        ),
    ]
